Repository pagarme/former-kit, pull requests merged in 2018-05, with the labels that each got.

#103 input: add props passthrough to inner input
  src/Input/Input.js
  stories/Input/default.js
Labels: devs, feature, review-needed

#105 Modal refactoring
  src/Modal/Modal.js
  src/Modal/ModalTitle.js
  stories/Modal/index.js
  stories/__snapshots__/storyshots.test.js.snap
Labels: devs, review-needed

#78 progress: refactor component
  src/LinearProgress/LinearProgress.test.js
  src/LinearProgress/example/style.css
  src/LinearProgress/index.js
  src/LinearProgress/index.md
  stories/Progress/index.js
  stories/Progress/style.css
  stories/__snapshots__/storyshots.test.js.snap
Labels: devs, review-needed

#106 Refactor modal styleguide
  src/Modal/README.md
  src/Modal/examples/ModalWithState.js
Labels: devs, review-needed

#107 card: remove hr class
  src/Card/CardSectionDoubleLineTitle.js
  stories/Card/CardExamples.js
  stories/Modal/index.js
  stories/__snapshots__/storyshots.test.js.snap
Labels: devs, review-needed

#118 date-input: fix end string width
  src/DateInput/examples/DateInputState.js
  src/DateInput/examples/style.css
  src/DateInput/index.js
  stories/DateInput/index.js
  stories/__snapshots__/storyshots.test.js.snap
Labels: devs, review-needed

#117 popover: fix export component
  src/index.js
Labels: devs, in-progress

#114 legend: remove outline prop
  src/Legend/Legend.test.js
  src/Legend/index.js
  stories/Legend/index.js
Labels: devs, review-needed

#113 modal: refactor close button size
  src/Modal/ModalTitle.js
  stories/__snapshots__/storyshots.test.js.snap
Labels: devs, review-needed

#81 sidebar: refactor component
  src/Layout/examples/SidebarState.js
  src/Sidebar/README.md
  src/Sidebar/Sidebar.js
  src/Sidebar/SidebarLink.js
  src/Sidebar/SidebarLink.test.js
  src/Sidebar/SidebarLinks.js
  src/Sidebar/SidebarSections.js
  src/Sidebar/index.js
  stories/Sidebar/SidebarState.js
  stories/Sidebar/logo.svg
  stories/__snapshots__/storyshots.test.js.snap
Labels: devs, in-progress, review-needed

#115 Refactor steps: add new status and remove background color
  src/Steps/Step.js
  src/Steps/index.js
  src/Steps/index.md
  stories/Steps/index.js
  stories/__snapshots__/storyshots.test.js.snap
Labels: devs, review-needed

#122 alert: add aria and role
  src/Alert/index.js
  stories/__snapshots__/storyshots.test.js.snap
Labels: devs, review-needed

#121 card: refactor stories
  stories/Card/CardExamples.js
  stories/Card/index.js
  stories/__snapshots__/storyshots.test.js.snap
Labels: devs, review-needed
