Repository pagarme/former-kit, pull requests merged in 2018-04, with the labels that each got.

#64 button: refactor style
  src/Button/index.js
  src/Button/index.md
  src/DateSelector/index.js
  src/Modal/README.md
  stories/Button/index.js
  stories/Landing/Login.js
  stories/Landing/PasswordRecovery.js
  stories/Landing/PasswordRecoveryConfirmation.js
  stories/Landing/SignIn.js
  stories/Landing/SignInConfirmation.js
  stories/Landing/style.css
  stories/Modal/index.js
  stories/__snapshots__/storyshots.test.js.snap
Labels: devs, review-needed

#73 pagination: refactor style
  src/Pagination/index.js
Labels: devs, review-needed

#71 date-selector: refactor style
  src/DateSelector/index.js
Labels: devs, review-needed

#76 Fix translation strings prop
  src/DateInput/index.js
  stories/DateInput/index.js
  stories/__snapshots__/storyshots.test.js.snap
Labels: devs, review-needed

#75 table: refactor style
  src/Table/TableAggregationRow.js
  src/Table/TableEmptyItem.js
  src/Table/TableExpandedItem.js
  src/Table/TableExpandedRow.js
  src/Table/TableHead.js
  src/Table/TableRow.js
  src/Table/index.js
Labels: devs, review-needed

#77 tab-bar: refactor style
  src/TabBar/TabBar.js
  src/TabBar/TabItem.js
  stories/TabBar/index.js
  stories/__snapshots__/storyshots.test.js.snap
Labels: devs, review-needed

#83 checkbox and radio: refactor components
  src/Checkbox/Checkbox.js
  src/Checkbox/Checkbox.md
  src/Checkbox/Checkbox.test.js
  src/Checkbox/examples/CheckboxForm.js
  src/Checkbox/examples/CheckboxState.js
  src/CheckboxGroup/CheckboxGroup.test.js
  src/CheckboxGroup/examples/CheckboxGroupState.js
  src/CheckboxGroup/index.js
  src/CheckboxGroup/index.md
  src/RadioGroup/examples/RadioGroupState.js
  src/RadioGroup/index.js
  src/RadioGroup/index.md
  src/Table/tests/Table.static.test.js
  stories/Checkbox/default.js
  stories/Checkbox/form.js
  stories/CheckboxGroup/index.js
  stories/RadioGroup/index.js
  stories/__snapshots__/storyshots.test.js.snap
Labels: devs, review-needed

#85 tooltip: add component
  config/styleguide.config.js
  src/Tooltip/example/index.js
  src/Tooltip/example/style.css
  src/Tooltip/index.js
  src/Tooltip/index.md
  stories/Tooltip/index.js
  stories/Tooltip/style.css
  stories/__snapshots__/storyshots.test.js.snap
  stories/index.js
Labels: review-needed

#87 Button: add iconPosition prop
  src/Button/index.js
  stories/Button/index.js
  stories/__snapshots__/storyshots.test.js.snap
Labels: review-needed

#95 switch: add name prop
  src/Switch/Switch.test.js
  src/Switch/index.js
  src/Switch/index.md
  stories/__snapshots__/storyshots.test.js.snap
Labels: review-needed

#96 dropdown: fix render when a value is provided
  src/Dropdown/Dropdown.js
  stories/Dropdown/default.js
  stories/Dropdown/form.js
  stories/__snapshots__/storyshots.test.js.snap
Labels: bug-fix, devs, review-needed

#99 tooltip: fix export tooltip component
  src/index.js
Labels: devs, review-needed

#98 steps: add component
  config/styleguide.config.js
  src/Steps/Step.js
  src/Steps/Steps.test.js
  src/Steps/index.js
  src/Steps/index.md
  src/index.js
  stories/Steps/index.js
  stories/__snapshots__/storyshots.test.js.snap
  stories/index.js
Labels: devs, review-needed

#100 Add table empty row
  src/Table/README.md
  src/Table/TableEmptyRow.js
  src/Table/examples/TableState.js
  src/Table/index.js
  src/Table/tests/Table.static.test.js
  src/Table/tests/common.js
  stories/Table/TableState.js
  stories/Table/index.js
  stories/__snapshots__/storyshots.test.js.snap
Labels: devs, feature, review-needed

#91 input: add new handle props
  src/Input/Input.js
  stories/Input/form.js
  stories/__snapshots__/storyshots.test.js.snap
Labels: review-needed

#101 header: add popover to header-menu
  src/Header/HeaderMenu.js
  stories/Header/HeaderContentExample.js
  stories/Popover/index.js
  stories/__snapshots__/storyshots.test.js.snap
Labels: devs, review-needed

#102 card-section: update props validation
  src/Card/CardSection.js
Labels: devs, review-needed

#86 readme: add starter dashboard link
  README.md
Labels: review-needed
