Repository pagarme/former-kit, pull requests merged in 2019-01, with the labels that each got.

#211 chore: update depencies patch version
  package.json
  yarn.lock
Labels: bug-fix, devs

#212 Fix/popover animation
  src/Popover/Popover.js
  src/Transition/Transition.md
  src/Transition/animation/fade.js
  src/Transition/animation/grow.js
  src/Transition/animation/zoom.js
  src/Transition/index.js
  src/index.js
  stories/Transition/index.js
Labels: bug-fix, cos:expedite

#208 date-selector: add selectedPreset prop
  src/DateSelector/index.js
  stories/DateSelector/index.js
  stories/__snapshots__/storyshots.test.js.snap
Labels: devs, review-needed

#216 update version to 0.11.0
  package.json
  yarn.lock
Labels: devs, review-needed
