Repository pagarme/former-kit, pull requests merged in 2019-04, with the labels that each got.

#252 Update react version
  package.json
  yarn.lock
Labels: cos:intangible, devs, review-needed

#253 chore: bump version to v1.3.0
  package.json
Labels: cos:intangible, devs, review-needed

#254 date-input: add moment peer dependency and add mask prop
  package.json
Labels: bug-fix, devs, review-needed

#255 button: add a loading state
  .babelrc
  package.json
  src/Button/index.js
  src/Button/index.md
  stories/Button/ButtonLoading.js
  stories/Button/index.js
  stories/__snapshots__/storyshots.test.js.snap
  yarn.lock
Labels: devs, review-needed

#261 release v1.4.0
  package.json
  yarn.lock
Labels: bug-fix, cos:standard, devs, review-needed

#258 Update/pagination
  src/Pagination/Pagination.test.js
  src/Pagination/index.js
  src/Pagination/index.md
  stories/Pagination/index.js
  stories/__snapshots__/storyshots.test.js.snap
Labels: cos:standard, devs, review-needed
