Repository pagarme/former-kit, pull requests merged in 2019-12, with the labels that each got.

#313 add format property to Legend component
  src/Legend/index.js
  stories/Legend/index.js
  stories/__snapshots__/storyshots.test.js.snap
Labels: cos:standard, devs

#311 Fix input type phone
  src/Input/Input.js
  stories/Input/default.js
  stories/Input/form.js
  stories/__snapshots__/storyshots.test.js.snap
Labels: bug-fix, cos:standard, devs

#315 Release 1.7.4
  package.json
  yarn.lock
Labels: bug-fix, cos:standard
