Repository pagarme/former-kit, pull requests merged in 2019-08, with the labels that each got.

#288 DateSelector - add placement prop
  src/DateSelector/index.js
  stories/DateSelector/index.js
  stories/__snapshots__/storyshots.test.js.snap
Labels: devs, review-needed

#289 Update version and dependencies
  package.json
  yarn.lock
Labels: devs, review-needed

#292 Date Input: Fix momentToText validation
  src/DateInput/index.js
Labels: bug-fix, devs, review-needed

#290 Update font family and examples
  stories/Card/CardSectionDoubleLineTitle.js
  stories/Typography/index.js
  stories/__snapshots__/storyshots.test.js.snap
Labels: cos:intangible, devs, review-needed
