Repository pagarme/former-kit, pull requests merged in 2019-07, with the labels that each got.

#276 Remove react memo from Truncate
  src/Truncate/index.js
Labels: cos:standard, devs, in-progress

#278 DateInput - Refactor selectedPreset usage
  src/DateInput/index.js
Labels: devs, review-needed

#282 Release 1.5.3
  package.json
  yarn.lock
Labels: bug-fix, cos:standard

#280 SegmentedSwitch - Add props for relevance and spacing
  src/SegmentedSwitch/SegmentedSwitch.js
  stories/SpacedSegmentedSwitch/index.js
  stories/__snapshots__/storyshots.test.js.snap
Labels: devs, review-needed

#284 DateInput - Fix preset and mode selection
  src/DateInput/index.js
Labels: bug-fix, devs, review-needed

#285 Update version
  package.json
  yarn.lock
Labels: cos:standard, devs, review-needed
