Repository pagarme/former-kit, pull requests merged in 2019-06, with the labels that each got.

#266 Tooltip: Add classname prop
  src/Tooltip/index.js
Labels: devs, review-needed

#269 Release 1.5.2
  package.json
  yarn.lock
Labels: cos:standard

#270 Add a new props to Modal component: size
  jest.config.js
  src/Modal/Modal.js
  src/Modal/Modal.md
  src/Modal/examples/ModalWithState.js
  stories/Modal/ModalWithHugeSize.js
  stories/Modal/ModalWithState.js
  stories/Modal/index.js
  stories/__snapshots__/storyshots.test.js.snap
Labels: devs, review-needed

#274 Fix DateInput presets
  src/DateInput/index.js
  stories/DateInput/index.js
  stories/DateInput/style.css
  stories/__snapshots__/storyshots.test.js.snap
Labels: bug-fix, cos:standard, devs, review-needed

#275 Fix DateInput presets
  src/DateInput/index.js
Labels: cos:standard, devs, review-needed
