Repository pagarme/former-kit, pull requests merged in 2019-02, with the labels that each got.

#217 Update dependencies
  .babelrc
  .circleci/config.yml
  config/styleguide.config.js
  config/webpack.config.storybook.js
  package.json
  scripts/test.js
  src/Button/index.js
  src/Calendar/Calendar.test.js
  src/Calendar/index.js
  src/CalendarInput/CalendarInput.test.js
  src/CalendarInput/index.js
  src/DateSelector/DateSelector.test.js
  src/DateSelector/index.js
  src/Modal/Modal.js
  src/Popover/Popover.js
  src/Sidebar/SidebarLink.test.js
  stories/Typography/style.css
  stories/__snapshots__/storyshots.test.js.snap
  yarn.lock
Labels: bug-fix, cos:standard, devs, review-needed

#221 Chore/add prepublish
  package.json
  yarn.lock
Labels: devs, review-needed

#224 dropdown: fix prop value
  src/Dropdown/Dropdown.js
  stories/__snapshots__/storyshots.test.js.snap
Labels: bug-fix, devs

#225 sidebar: add expanded className and removes SidebarContent component
  src/Layout/examples/SidebarState.js
  src/Sidebar/README.md
  src/Sidebar/Sidebar.js
  src/Sidebar/index.js
  stories/Sidebar/SidebarState.js
  stories/__snapshots__/storyshots.test.js.snap
Labels: devs, review-needed, uxs

#227 Add/snackbar
  src/Snackbar/Snackbar.test.js
  src/Snackbar/examples/SnackbarWithState.js
  src/Snackbar/examples/Timer.js
  src/Snackbar/examples/style.css
  src/Snackbar/index.js
  src/Snackbar/index.md
  src/Transition/animation/fold.js
  src/Transition/index.js
  src/index.js
  stories/Modal/index.js
  stories/Snackbar/index.js
  stories/Transition/index.js
  stories/__snapshots__/storyshots.test.js.snap
  stories/index.js
Labels: review-needed

#229 Refactor Tag component props
  src/Tag/index.js
Labels: bug-fix, devs, review-needed

#236 Fix styleguide settings
  config/styleguide.config.js
Labels: devs, review-needed
