Repository pagarme/former-kit, pull requests merged in 2019-03, with the labels that each got.

#234 DateInput - Adiciona no input a data do preset pré-selecionado
  package.json
  src/Calendar/index.js
  src/CalendarInput/index.js
  src/DateInput/index.js
  src/DateSelector/index.js
  src/index.js
  src/validations/index.js
  src/validations/momentProp.js
  stories/__snapshots__/storyshots.test.js.snap
  yarn.lock
Labels: bug-fix, devs, review-needed

#239 chore: update version to 1.2.0
  package.json
Labels: bug-fix, cos:standard, devs, review-needed

#243 update version to 1.2.1
  package.json
Labels: bug-fix, cos:standard, devs, review-needed

#238 table: add loader table row component
  config/styleguide.config.js
  src/Calendar/index.js
  src/DateSelector/index.js
  src/Table/TableLoadingRow.js
  src/Table/examples/TableLoader.js
  src/Table/index.js
  src/Table/index.md
  src/Table/tests/Table.behaviour.test.js
  src/Table/tests/common.js
  stories/Table/TableStateLoading.js
  stories/Table/index.js
  stories/__snapshots__/storyshots.test.js.snap
Labels: cos:standard, devs, portal-terra, review-needed

#246 Fix/snackbar
  config/styleguide.config.js
  src/Snackbar/index.md
  stories/Snackbar/SnackbarWithState.js
  stories/Snackbar/Timer.js
  stories/Snackbar/index.js
  stories/Snackbar/style.css
Labels: devs, review-needed

#248 table-loader-row: update colspan handlers
  src/Table/index.js
Labels: devs, review-needed

#250 chore: update range version from package
  package.json
  yarn.lock
Labels: cos:intangible, devs, review-needed
