Repository pagarme/former-kit, pull requests merged in 2019-11, with the labels that each got.

#305 legend: add textColor prop
  src/Legend/index.js
  stories/__snapshots__/storyshots.test.js.snap
Labels: devs, review-needed

#306 release 1.7.2
  package.json
  yarn.lock
Labels: cos:standard

#307 Dateinput - Updates focus usability
  src/DateInput/index.js
  src/DateSelector/index.js
Labels: devs, review-needed

#309 Release 1.7.3
  package.json
  yarn.lock
Labels: cos:standard, review-needed
