Repository pagarme/former-kit, pull requests merged in 2020-02, with the labels that each got.

#317 Add/progress bar
  src/LinearProgress/LinearProgress.js
  src/LinearProgress/LinearProgress.md
  src/LinearProgress/SecondaryLinearProgress/index.js
  src/LinearProgress/index.js
  src/index.js
  stories/Progress/default.js
  stories/Progress/index.js
  stories/Progress/secondaryLinearProgress.js
  stories/__snapshots__/storyshots.test.js.snap
Labels: help-wanted, review-needed

#319 Release v1.8.0
  package.json
  yarn.lock
Labels: cos:standard, devs

#320 segmented-switch: add classname prop
  src/SegmentedSwitch/SegmentedSwitch.js
Labels: devs, review-needed

#321 Release v1.8.1
  package.json
  src/SegmentedSwitch/SegmentedSwitch.js
Labels: devs, review-needed
