Repository pagarme/former-kit, pull requests merged in 2020-03, with the labels that each got.

#325 Adiciona tamanho mobile no componente Modal
  src/Modal/Modal.js
  stories/Modal/ModalWithMobileSize.js
  stories/Modal/index.js
  stories/__snapshots__/storyshots.test.js.snap
Labels: cos:intangible, devs

#327 release 1.8.2
  package.json
  yarn.lock
Labels: cos:standard

#323 Add/secondary button
  src/Button/Button.js
  src/Button/Button.md
  src/Button/SecondaryButton/index.js
  src/Button/index.js
  src/index.js
  stories/Button/default.js
  stories/Button/index.js
  stories/Button/secondaryButton.js
  stories/__snapshots__/storyshots.test.js.snap
Labels: cos:standard, devs, feature

#329 dropdown: add SecondaryDropdown
  src/Dropdown/Dropdown.js
  src/Dropdown/secondary-form/index.js
  stories/Dropdown/index.js
  stories/Dropdown/secondaryForm.js
  stories/__snapshots__/storyshots.test.js.snap
Labels: cos:standard, help-wanted, review-needed

#330 release 1.9.0
  package.json
  yarn.lock
Labels: cos:standard

#332 release 1.9.1
  package.json
Labels: cos:standard
